export enum SlashItemKey {
  TodoList = 'TodoList',
  BulletList = 'BulletList',
  NumberedList = 'NumberedList',
  Quote = 'Quote',
  Code = 'Code',
  Image = 'Image',
  Table = 'Table',
  Heading1 = 'Heading1',
  Heading2 = 'Heading2',
  Heading3 = 'Heading3',
  Heading4 = 'Heading4',
  Heading5 = 'Heading5',
  Heading6 = 'Heading6',
  Text = 'Text',
  AddRowAfter = 'AddRowAfter',
  AddRowBefore = 'AddRowBefore',
  AddColAfter = 'AddColAfter',
  AddColBefore = 'AddColBefore',
  DelRow = 'DelRow',
  DelCol = 'DelCol'
}
